version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    network_mode: "bridge"
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
    network_mode: "bridge"
    restart: always

  metabse:
    image: metabase/metabase:v0.35.4
    expose:
      - "3000"
    environment:
      # nginx-proxy
      VIRTUAL_HOST: metabase.example.com
      VIRTUAL_PORT: 80
      # letsencrypt
      LETSENCRYPT_HOST: metabase.example.com
      LETSENCRYPT_EMAIL: admin@example.com
      # Metabase
      JAVA_TIMEZONE: Asia/Tokyo
      JAVA_TOOL_OPTIONS: -Xmx1000m
      MB_DB_DBNAME: ops-metabse
      MB_DB_HOST: xxxxxxxxxxxx-cluster.cluster-xxxxxxxxxxxx.us-west-2.rds.amazonaws.com
      MB_DB_PASS: xxxxxxxxxxxx
      MB_DB_PORT: 3306
      MB_DB_TYPE: mysql
      MB_DB_USER: meta_user
    network_mode: "bridge"
    restart: always
